spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/test
server:
  port: 9091
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false